import type { Metadata, Viewport } from 'next'
import { DM_Sans, Space_Mono, Instrument_Serif, Geist } from 'next/font/google'
import Script from 'next/script'
import { AuthFeedback } from '@/components/auth-feedback'
import './globals.css'
import { cn } from '@/lib/utils'

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' })

const sans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
})

const title = Instrument_Serif({
  variable: '--font-title',
  subsets: ['latin'],
  weight: ['400'],
})

const mono = Space_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Undersland',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/icon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/icon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/icon-48x48.png', sizes: '48x48', type: 'image/png' },
      { url: '/icon-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
    shortcut: '/favicon.ico',
    apple: '/apple-icon.png',
  },
}

export const viewport: Viewport = {
  colorScheme: 'light dark',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#18181b' },
  ],
}

const themeScript = `
  (() => {
    const root = document.documentElement;
    const media = window.matchMedia('(prefers-color-scheme: dark)');

    const applyTheme = () => {
      const savedTheme = localStorage.getItem('theme');
      const isSystem = savedTheme === null || savedTheme === 'system';
      const isDark = savedTheme === 'dark' || (isSystem && media.matches);

      root.classList.toggle('dark', isDark);
      root.style.colorScheme = isDark ? 'dark' : 'light';
    };

    applyTheme();
    media.addEventListener('change', applyTheme);
  })();
`

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        sans.variable,
        mono.variable,
        title.variable,
        'font-sans',
        geist.variable,
      )}
      suppressHydrationWarning
    >
      <head>
        <Script id="theme-initializer" strategy="beforeInteractive">
          {themeScript}
        </Script>
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        {/* <AuthFeedback /> */}
        <div className="fixed top-0 right-0 left-0 flex h-5 sm:h-7 px-10 items-center justify-center bg-red-700">
          <p className="text-[9px] sm:text-[11px] font-semibold tracking-wider text-white uppercase truncate">
            This version is in the testing phase and is subject to errors.
          </p>
        </div>
      </body>
    </html>
  )
}
